name = "Arcdoor Forever Pack"
author = "Kedan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acf7a45e1c3f352ed4d709dad6b7aa27e18517cdce9cff714c4d13a4cf2458e5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
