name = "Arcdoor Forever Pack"
author = "Kedan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7826c44e30bf8c437cff2823cedb8fa549ca5a61e45f69e7fef2a69e44f72ed1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
