name = "Arcdoor Forever Pack"
author = "Kedan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ddd1798fcca2a0e2a665745a6d9b59da15a675b7a63474307cd63183552d0d9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
